# Site Settings
lang: en

title: US-RSE Gallery
description: The US-RSE Gallery

url: ""
baseurl: "/gallery"  # for testing, also check .circleci/circle_urls.sh
title-img: /assets/img/main_logo_transparent.png  # baseurl will be prepended
twitter-img: /assets/img/main_logo_transparent.png  # url + baseurl will be prepended
banner: /assets/img/main_logo_transparent.png
icon: /assets/img/main_logo_transparent.png

email: contact@us-rse.org
permalink: /:year-:month-:day-:title/

favicon: /assets/img/favicon.ico
#hide_share_buttons: true
#theme_color: '#eeeeee'
fixed_navbar: top

excerpt_length: 500

# social media
twitter: us_rse
github_org: USRSE
linkedin: company/us-rse/

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

livereload: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true


markdown: kramdown
highlighter: rouge
